

services:
  postgres:
    image: ankane/pgvector
    container_name: pgvector-db
    restart: always
    environment:
      POSTGRES_USER: arnav
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: core_db
    ports:
      - "5432:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data

volumes:
  pgvector-data:
