/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("com.typesafe:config:1.4.4")
    implementation("org.slf4j:slf4j-api:2.0.9")
    implementation("ch.qos.logback:logback-classic:1.4.11")

implementation("com.google.protobuf:protobuf-java:3.25.3")
implementation("io.grpc:grpc-stub:1.68.1")
implementation("io.grpc:grpc-protobuf:1.68.1")
implementation("io.grpc:grpc-netty-shaded:1.68.1")
    implementation("redis.clients:jedis:5.1.0")
    compileOnly("javax.annotation:javax.annotation-api:1.3.2") // needed by grpc stubs
        implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.2")



}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.Tyche.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
// tasks.register<Exec>("bufGenerate") {
//     commandLine("buf", "generate")
//     inputs.dir("src/main/proto")
//     outputs.dir("build/generated/source/proto/main")
// }

// tasks.named("compileJava") {
//     dependsOn("bufGenerate")
// }

sourceSets {
    main {
        java {
            srcDirs(
                "src/main/java",
                "build/generated/source/proto/main/java",
                "build/generated/source/proto/main/grpc"
            )
        }
    }
}